# MySQL database configuration for the Mysql2 gem.
database:
  host: 127.0.0.1
  database: database_name
  username: root
  password:

# The primary key name shared common to all/most tables.
primary_key: id

# The timestamp column shared common to all/most tables.
timestamp: updated_at

# The batch size to use when searching for updates using the pk strategy.
batch_size: 10000

# Indicates how many times the pk strategy will loop with empty results.
max_empty_loops: 10

# The directory where the archived files will be save.
path: /path/to/archived/files

# The storage strategy to use on the filesystem.
# * structured - directories are created for each table and data files are stored in the appropriate table directories
# * flat - all files are stored directly under /[path] Note that the schema will be still be stored in table directories
storage_strategy: flat

# The delimiter to use as a column separator in the CSV files.
csv_delimiter: ","
